In [1]:
from tictactoe import game
from collections import deque
import os
import pickle
import sys
sys.path.append(os.path.join('tictactoe'))
from tictactoe import train
import numpy as np
import tensorflow as tf

In [6]:
#example state
ttt = game.TicTacToe()
ttt.play_move(0, 0, False)
ttt.play_move(0, 1, False)
ttt.play_move(1, 0, False)
ttt.play_move(1, 1, True)
# ttt.play_move(0, 2)

| X | O |   |
| X | O |   |
|   |   |   |


In [7]:
state = train.board_state_int(ttt.board, 2)
state[:, :, 2]

array([[0., 0., 2.],
       [0., 0., 2.],
       [2., 2., 2.]])

In [8]:
#load model
#import models
from models import RecurrentNetwork as rn

#initialize model
model = rn.RecurrentNN
model.build(input_shape = (None, 3, 3, 3))
#simpler model
# model = tf.keras.Sequential([
#     tf.keras.layers.Flatten(input_shape=(3, 3, 3)),  # Flatten the 3x3x3 input
#     tf.keras.layers.Dense(128, activation='relu'),
#     tf.keras.layers.Dense(64, activation='relu'),
#     tf.keras.layers.Dense(9, activation='linear')   # Output layer with 9 units for the Q-values
# ])

# model.build(input_shape = (None, 3, 3, 3))

#weights dir
weights_dir = os.path.join('model_weights', 'RecurrentNetwork', 'model_weight_episode_5750.h5')

model.load_weights(weights_dir)

In [9]:
np.argmax(model.predict(state[np.newaxis, :]))

0

In [10]:
model.predict(state[np.newaxis, :])

array([[ 38.384068, -21.916683, -15.02494 ,  38.169903, -16.094847,
         37.976357, -21.41896 ,  37.636032, -16.871252]], dtype=float32)

In [11]:
ttt = game.TicTacToe()

ttt.play_move(0, 2, False)
ttt.play_move(0, 1, False)
ttt.play_move(1, 1, False)
ttt.play_move(2, 2)

|   | O | X |
|   | X |   |
|   |   | O |


In [127]:
state = train.board_state_int(ttt.board, 1)
state[:, :, 0]

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [128]:
np.argmax(model.predict(state[np.newaxis, :]))

5

In [120]:
model.input_shape

(None, 3, 3, 3)

In [84]:
model.output_shape

(None, 9)

In [85]:
#load the memory
memory_dir = os.path.join('model_weights', 'RecurrentNetwork', 'memory_episode_60.pkl')

with open(memory_dir, 'rb') as file:
    memory = pickle.load(file)

FileNotFoundError: [Errno 2] No such file or directory: 'model_weights\\RecurrentNetwork\\memory_episode_60.pkl'

In [58]:

len(memory)

467

In [61]:
i = 21

print(memory[i][0][:, :, 2])
print(memory[i][1][:, :, 2])
print(memory[i][2])
print(memory[i][3])

[[0. 0. 0.]
 [2. 0. 2.]
 [2. 2. 0.]]
[[0. 0. 0.]
 [1. 0. 1.]
 [1. 0. 0.]]
(2, 1)
0
